name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    services:
      rabbitmq:
        image: rabbitmq
        ports:
        - 5672/tcp

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - ocaml-base-compiler.5.0.0~rc1
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true

      - run: opam install . --deps-only --with-test
      - run: opam exec -- dune build
      - run: opam exec -- dune runtest

      - run: opam exec -- dune build @integration -p amqp_client_eio
        env:
          AMQP_PORT: ${{ job.services.rabbitmq.ports[5672] }}
